import type {
  HotelDeal,
  HotelDetails,
  HotelProviderAdapter,
  HotelSearchResult,
} from "@/lib/hotelProviders/types";
import { HotelProviderAdapterError } from "@/lib/hotelProviders/types";

// ============================================================================
// AUTHENTICATION: CONFIRMED. ENDPOINT REQUEST/RESPONSE SHAPES: NOT CONFIRMED.
//
// Verified 2026-09-24 against Booking.com's own developer documentation:
//   - https://developers.booking.com/demand/docs/development-guide/authentication
//   - https://developers.booking.com/demand/docs/getting-started/sandbox
//   - https://developers.booking.com/demand/docs/open-api/demand-api
// This environment's web-fetch tooling could not load developers.booking.com
// directly (blocked by this session's network egress policy), so the facts
// below come from two independent web searches whose results quoted and
// paraphrased those exact pages - including a literal example request - not
// from a page this session rendered and read itself. Re-confirm directly
// against the live docs (they're a normal login away, no partner status
// needed just to read them) before connecting real traffic.
//
// CONFIRMED:
//   - Auth: every request carries two headers - `Authorization: Bearer
//     <token>` and `X-Affiliate-Id: <affiliate id>`. HTTPS is required;
//     Booking.com rejects plain HTTP.
//   - There is no self-service application and no keyless/public tier.
//     Credentials are generated by logging into the Affiliate Partner
//     Centre (access provisioned by a Booking.com Account Manager) and
//     creating an API key (bearer token) there.
//   - Getting that login in the first place requires: Managed Affiliate
//     Partner status with Booking.com, and a signed partner contract.
//   - A sandbox exists at https://demandapi-sandbox.booking.com and uses
//     the exact same credentials as production (no separate sandbox key) -
//     it simulates search/booking/payment/cancellation without real
//     charges. Booking.com's own example:
//       curl --request POST 'https://demandapi-sandbox.booking.com/3.1/accommodations/search' \
//         --header 'X-Affiliate-Id: 123456' \
//         --header 'Authorization: Bearer xyz.........xyz' \
//         --data-raw '{ "city": -2140479, ... }'
//   - Booking.com recommends rotating the API key every 12 months.
//
// NOT CONFIRMED - do not guess these; read them from the live OpenAPI spec
// once partner access exists, then implement the methods below for real:
//   - The full request body for accommodations/search (only a partial
//     example was visible - a `city` field holding a Booking.com internal
//     location id; the rest, including check-in/out and guest/room
//     counts, is unconfirmed) or the response body shape for search,
//     accommodation details, or availability.
//   - The affiliate deep-link/redirect URL format - how a guest is
//     actually sent to Booking.com's site with this affiliate's tracking
//     attached. This is the single most important thing to confirm before
//     Phase 7 (click tracking + redirect) can be built for real.
//   - Whether production is exactly "https://demandapi.booking.com"
//     (inferred here only by dropping "-sandbox" from the confirmed
//     sandbox host - never independently confirmed).
//   - The exact API version path segment to integrate against - both
//     "3.1" (in the example above) and "3.2-beta" appear across
//     Booking.com's own documentation URLs.
//
// What's needed before this file can do more than validate credentials:
//   1. Booking.com Managed Affiliate Partner status + a signed contract.
//   2. Partner Centre access (from an Account Manager) to generate the
//      affiliate ID and API bearer token.
//   3. A read of the live OpenAPI spec for the endpoints this adapter
//      needs, and Booking.com's own affiliate deep-link documentation.
// ============================================================================

const BOOKING_COM_SANDBOX_BASE_URL = "https://demandapi-sandbox.booking.com";

/**
 * Reads and validates the two required credentials, throwing a clear,
 * non-retryable error naming exactly what's missing if either is unset.
 * Called first by every method below - "missing credentials fail safely
 * and clearly" is true for this adapter regardless of which method is
 * called, not just the ones that happen to reach a real fetch() one day.
 * Credentials never reach the browser by construction, not by a runtime
 * guard: this file - like every other provider adapter in this codebase
 * (see src/lib/pms/providers/*.ts) - is only ever imported from
 * server-side code (an API route, a server component), never from a
 * "use client" module.
 */
function getBookingComCredentials(): { apiKey: string; affiliateId: string; baseUrl: string } {
  const apiKey = process.env.BOOKING_COM_API_KEY;
  const affiliateId = process.env.BOOKING_COM_AFFILIATE_ID;
  if (!apiKey || !affiliateId) {
    throw new HotelProviderAdapterError(
      "Booking.com is not configured: set BOOKING_COM_API_KEY and BOOKING_COM_AFFILIATE_ID " +
        "(both issued via the Booking.com Affiliate Partner Centre - see this file's own top " +
        "comment for how to obtain them) before this provider can be used. Use the mock " +
        "provider (src/lib/hotelProviders/providers/mock.ts) for development and testing.",
      { retryable: false },
    );
  }
  // Defaults to Booking.com's own confirmed sandbox host - production is
  // never used unless BOOKING_COM_API_BASE_URL is explicitly set to it, so
  // a deployment that sets credentials without separately deciding which
  // environment to target can never accidentally hit production.
  const baseUrl = process.env.BOOKING_COM_API_BASE_URL || BOOKING_COM_SANDBOX_BASE_URL;
  return { apiKey, affiliateId, baseUrl };
}

function notYetConfirmed(method: string): never {
  throw new HotelProviderAdapterError(
    `booking_com.${method}: credentials are configured, but this endpoint's request/response ` +
      `shape has not yet been confirmed against Booking.com's live OpenAPI spec (see this ` +
      `file's own top comment). Implementing it now would mean inventing a request format, ` +
      `which this integration's own rules explicitly forbid. Confirm the shape at ` +
      `https://developers.booking.com/demand/docs/open-api/demand-api, then fill in this method.`,
    { retryable: false },
  );
}

export const bookingComAdapter: HotelProviderAdapter = {
  code: "booking_com",
  name: "Booking.com",

  // Declared true because Booking.com's Demand API is expected to support
  // all of these once fully connected - these flags describe the
  // provider's real capabilities, not whether FYStay has finished wiring
  // up to them yet. supportsConversionTracking stays false until
  // Booking.com's reporting/postback access is specifically confirmed for
  // this app's approved partner program.
  supportsSearch: true,
  supportsDeepLink: true,
  supportsClickTracking: true,
  supportsConversionTracking: false,

  async searchHotels(): Promise<HotelSearchResult[]> {
    getBookingComCredentials();
    notYetConfirmed("searchHotels");
  },

  async getHotelDetails(): Promise<HotelDetails> {
    getBookingComCredentials();
    notYetConfirmed("getHotelDetails");
  },

  async getAvailability(): Promise<HotelDeal[]> {
    getBookingComCredentials();
    notYetConfirmed("getAvailability");
  },

  createDeepLink(): string {
    getBookingComCredentials();
    notYetConfirmed("createDeepLink");
  },
};
